Added maxRows to NetworkLogger
alexbrazier/react-native-network-logger pull request #91
Opened 2023-12-19 02:15 UTC by jwallet

To limit the amount of data passed to NetworkLogger child components and prevent re-rendering too much data, we can now pass `maxRows` to NetworkLogger

compared to `maxRequests` which pop() the last one to prevent recording more than the max. `maxRows` is only visual, the request won't be lost if it is kept inside the main logger.

2023-12-19 15:53 UTC, jwallet commented on src/components/NetworkLogger.spec.tsx
> +  });
```suggestion
  it('should clear the logs on demand', () => {
    const spyOnLoggerClearRequests = jest.spyOn(logger, 'clearRequests');

    const { getByText, getByTestId } = render(<MyNetworkLogger />);
    expect(spyOnLoggerClearRequests).toHaveBeenCalledTimes(0);

    fireEvent.press(getByTestId('options-menu'));
    fireEvent.press(getByText(/^clear/i));

    expect(spyOnLoggerClearRequests).toHaveBeenCalledTimes(1);

    spyOnLoggerClearRequests.mockRestore();
  });
```

2023-12-20 20:08 UTC, alexbrazier requested changes

2023-12-20 20:08 UTC, alexbrazier commented on src/components/Options.tsx
> +                onPress={() => {
Removing the `async/await` breaks the "Export all Logs" option on ios - the share dialog never opens. Can this be reverted or is there a reason for the change?

2023-12-21 12:27 UTC, jwallet commented on src/components/Options.tsx
> +                onPress={() => {
I changed it because I added tests for the NetworkLogger and the test thrown some warnings about pending setState after the test ended, I can add it back and move the setState before the await

2023-12-21 12:31 UTC, jwallet commented on src/components/Options.tsx
>                  }}
```suggestion
                onPress={async () => {
                  await onPress();
                  setOpenOptions(false);
                }}
```

2023-12-22 09:49 UTC, alexbrazier approved these changes

2023-12-22 15:54 UTC, alexbrazier approved these changes

2023-12-22 15:54 UTC, merged